// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIREA1yWVz2kU1Expw_xk4fq_TJWaD-FE',
    appId: '1:100159955058:web:216e2f861ef4846bbba2eb',
    messagingSenderId: '100159955058',
    projectId: 'seekr-8b019',
    authDomain: 'seekr-8b019.firebaseapp.com',
    storageBucket: 'seekr-8b019.firebasestorage.app',
    measurementId: 'G-5C71XN3YGJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7fyq-iOvIl7-YDRE13og3eDEcpbz7VeQ',
    appId: '1:100159955058:android:6ad2058810c5082abba2eb',
    messagingSenderId: '100159955058',
    projectId: 'seekr-8b019',
    storageBucket: 'seekr-8b019.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJ7GfYcFYJndWb3NDxBLDr50RhRypLnc',
    appId: '1:100159955058:ios:5851154d49794fa1bba2eb',
    messagingSenderId: '100159955058',
    projectId: 'seekr-8b019',
    storageBucket: 'seekr-8b019.firebasestorage.app',
    iosBundleId: 'com.example.seekr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdJ7GfYcFYJndWb3NDxBLDr50RhRypLnc',
    appId: '1:100159955058:ios:5851154d49794fa1bba2eb',
    messagingSenderId: '100159955058',
    projectId: 'seekr-8b019',
    storageBucket: 'seekr-8b019.firebasestorage.app',
    iosBundleId: 'com.example.seekr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIREA1yWVz2kU1Expw_xk4fq_TJWaD-FE',
    appId: '1:100159955058:web:2939b30961eb5df9bba2eb',
    messagingSenderId: '100159955058',
    projectId: 'seekr-8b019',
    authDomain: 'seekr-8b019.firebaseapp.com',
    storageBucket: 'seekr-8b019.firebasestorage.app',
    measurementId: 'G-9NSNFPPB59',
  );
}
